### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@734eead

### ISSUE THREAD

**Issue by mccccccmike** [google/AndroidForegroundCompat#1]
## Expected Behavior
No Exceptions thrown

## Actual Behavior
Fatal Exception: java.lang.RuntimeException
Canvas: trying to use a recycled bitmap android.graphics.Bitmap@734eead
android.graphics.BaseCanvas.throwIfCannotDraw (BaseCanvas.java:55)
android.view.View.draw (View.java:20373)
me.zhanghai.android.foregroundcompat.ForegroundImageView.draw (ForegroundImageView.java:66)
android.view.View.updateDisplayListIfDirty (View.java:19318)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

## Steps to Reproduce the Problem
Background
I am using RecyclerView to show a photos/videos list, so, I am using ForegroudImageView to show an item whether or not it's a photo or video, I got some crashes from firebase Crashlytics just like above Actual Behavior shown
in my adapter, I also do the following and don't know if it caused this issue
override fun onViewRecycled(holder: BaseViewHolder) {
        super.onViewRecycled(holder)
        Timber.d("onViewRecycled")

        holder.view.blurView?.clearBackground()

        holder.view.imageViewAuthor?.GlideClear()
        ((holder.view.media0?.tag) as? ImageView)?.GlideClear()
        ((holder.view.media1?.tag) as? ImageView)?.GlideClear()
        ((holder.view.media2?.tag) as? ImageView)?.GlideClear()
        ((holder.view.media3?.tag) as? ImageView)?.GlideClear()
        ((holder.view.media4?.tag) as? ImageView)?.GlideClear()
    }

fun ImageView.GlideClear() {
    GlideApp.with(context).clear(this)
}
1.
1.
1.

## Specifications

- Version:1.0.0
- Platform: 
 Android 8.0.0
 Galaxy A5(2017)

**Comment by zhanghai** [comment]
This library never recycles bitmap, so it is more likely something in your app code.
